### ISSUE TITLE
Integration von Gruppen

### ISSUE THREAD

**Issue by ChUrl** [hhu-propra2/abschlussprojekt-teamymcteamface#64]
Jo Leute, ich wollte mal fragen wie ihr bei euch die Integration von Gruppen handhabt (falls ihr sowas macht), damit wir wissen welche Informationen wir über unsere Api bereitstellen müssen. Wär also schön zu wissen ob ihr zum Beispiel eine Funktion zum allgemeinen Datenabgleich braucht, oder nur speziellere Anfragen nach einzelnen Gruppen (z.B.) stellt. Außerdem wollen wir wissen was für Informationen über Gruppen ihr bei euch verwendet (sowas wie Titel, Teilnehmer oder so).

Wir stimmen unsere Api dann mit den Senioren ab und stellen nur die nötigen Funktionen bereit.

Wenn ihr sowas gar nicht braucht einfach ignorieren :)

**Comment by smncrm** [comment]
Hallo hallo, 

wir haben heute mit den Senioren gesprochen und die Schnittstelle quasi abgeklärt. Da könntet ihr euch die Infos von denen auch holen :)

Generell:
wir brauchen gruppenids, gruppennamen, teilnehmer, wer ist admin, und wenn vorhanden: ist das eine offizielle gruppe, sprich: gehört die zu einem Kurs.
Wir würden in regelmäßigen Abständen diese Dinge anfragen.

Was ich der anderen Gruppe auch erklärt habe, was mega cool wäre:
Wir fragen regelmäßig ab und bekommen als Antwort nur die Änderungen seit der letzten Abfrage. Vllt gibt es so eine Versionshistorie direkt in euer DB und dann gebt ihr quasi jedes mal nen hash mit, den speichern wir und schicken den bei der nächsten Anfrage wieder mit: "Was ist seit diesem hash passiert?"
